In [ ]:
%tensorflow_version 2.x

In [ ]:
import numpy as np 
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [ ]:
from google.colab import drive
drive.mount("/content/drive/")

Mounted at /content/drive/


In [ ]:
%cd /content/drive/MyDrive/Deep Learning Bootcamp/week 4/

/content/drive/MyDrive/Deep Learning Bootcamp/week 4


In [ ]:
iris = pd.read_csv("Iris.csv")
iris

Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
1      2            4.9  ...           0.2     Iris-setosa
2      3            4.7  ...           0.2     Iris-setosa
3      4            4.6  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[150 rows x 6 columns]

In [ ]:
naya_variable = iris.iloc[:,[1,2,3,4]]

In [ ]:
naya_variable

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [ ]:
x_array = naya_variable.values

In [ ]:
y_array = iris.iloc[: ,6]

In [ ]:
y_array

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: class, Length: 150, dtype: int8

In [ ]:
y_array = y_array.values

In [ ]:
y_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int8)

In [ ]:
iris['class'] =  [0]*100 + [1]*50

In [ ]:
iris['Species']. dtype

dtype('O')

In [ ]:
iris['Species']= iris["Species"].astype('category') 

In [ ]:
iris['class'] = iris["Species"].cat.codes

In [ ]:
iris

Id  SepalLengthCm  SepalWidthCm  ...  PetalWidthCm         Species class
0      1            5.1           3.5  ...           0.2     Iris-setosa     0
1      2            4.9           3.0  ...           0.2     Iris-setosa     0
2      3            4.7           3.2  ...           0.2     Iris-setosa     0
3      4            4.6           3.1  ...           0.2     Iris-setosa     0
4      5            5.0           3.6  ...           0.2     Iris-setosa     0
..   ...            ...           ...  ...           ...             ...   ...
145  146            6.7           3.0  ...           2.3  Iris-virginica     2
146  147            6.3           2.5  ...           1.9  Iris-virginica     2
147  148            6.5           3.0  ...           2.0  Iris-virginica     2
148  149            6.2           3.4  ...           2.3  Iris-virginica     2
149  150            5.9           3.0  ...           1.8  Iris-virginica     2

[150 rows x 7 columns]

In [ ]:
x_train, x_test, y_train, y_test= train_test_split(x_array, y_array, test_size=0.1, shuffle = True, random_state = 50)

In [ ]:
x_train.shape

(135, 4)

In [ ]:
x_test.shape

(15, 4)

In [ ]:
y_train

array([0, 1, 0, 1, 1, 2, 1, 0, 2, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 0, 0, 1,
       2, 1, 0, 0, 1, 2, 0, 2, 0, 0, 0, 2, 2, 1, 0, 0, 1, 2, 1, 1, 0, 0,
       2, 2, 1, 2, 0, 0, 2, 1, 0, 1, 0, 2, 2, 1, 2, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 2, 2, 2, 1, 2, 0, 2, 0, 1, 0, 2, 0, 0, 2, 2, 2,
       2, 0, 2, 1, 2, 1, 0, 1, 2, 0, 2, 1, 1, 1, 1, 2, 1, 0, 2, 0, 2, 0,
       1, 2, 0, 0, 1, 2, 1, 0, 0, 0, 2, 1, 1, 2, 1, 1, 0, 2, 0, 2, 1, 2,
       0, 2, 2], dtype=int8)

In [ ]:
y_test

array([1, 1, 0, 0, 2, 2, 2, 0, 0, 1, 0, 2, 0, 2, 1], dtype=int8)

In [ ]:
model = tf.keras.models.Sequential()

In [ ]:
model.add(
    tf.keras.layers.Dense(32, input_shape = (4,), activation = 'relu')
)
model.add(
     tf.keras.layers.Dense(32, activation= 'relu')
)

model.add(
    tf.keras.layers.Dense(3, activation = 'softmax')
)

In [ ]:
model.compile(loss = "sparse_categorical_crossentropy", optimizer = 'rmsprop')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                160       
_________________________________________________________________
dense_1 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 33        
_________________________________________________________________
dense_3 (Dense)              (None, 32)                64        
_________________________________________________________________
dense_4 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 99        
Total params: 2,468
Trainable params: 2,468
Non-trainable params: 0
______________________________________________________

In [ ]:
model.fit(x_train, y_train, validation_split = 0.1, epochs=200 )

Epoch 1/200
4/4 [==============================] - 0s 12ms/step - loss: 0.4599 - val_loss: 0.5485
Epoch 2/200
4/4 [==============================] - 0s 7ms/step - loss: 0.4611 - val_loss: 0.5467
Epoch 3/200
4/4 [==============================] - 0s 5ms/step - loss: 0.4587 - val_loss: 0.5482
Epoch 4/200
4/4 [==============================] - 0s 6ms/step - loss: 0.4598 - val_loss: 0.5462
Epoch 5/200
4/4 [==============================] - 0s 6ms/step - loss: 0.4616 - val_loss: 0.5465
Epoch 6/200
4/4 [==============================] - 0s 6ms/step - loss: 0.4610 - val_loss: 0.5460
Epoch 7/200
4/4 [==============================] - 0s 7ms/step - loss: 0.4594 - val_loss: 0.5466
Epoch 8/200
4/4 [==============================] - 0s 6ms/step - loss: 0.4598 - val_loss: 0.5472
Epoch 9/200
4/4 [==============================] - 0s 5ms/step - loss: 0.4594 - val_loss: 0.5476
Epoch 10/200
4/4 [==============================] - 0s 6ms/step - loss: 0.4607 - val_loss: 0.5487
Epoch 11/200
4/4 [==========

In [ ]:
model.fit(x_train, y_train, validation_split = 0.1, epochs=100 )

Epoch 1/100
4/4 [==============================] - 0s 14ms/step - loss: 0.4609 - val_loss: 0.5465
Epoch 2/100
4/4 [==============================] - 0s 6ms/step - loss: 0.4584 - val_loss: 0.5464
Epoch 3/100
4/4 [==============================] - 0s 6ms/step - loss: 0.4589 - val_loss: 0.5453
Epoch 4/100
4/4 [==============================] - 0s 5ms/step - loss: 0.4599 - val_loss: 0.5449
Epoch 5/100
4/4 [==============================] - 0s 5ms/step - loss: 0.4604 - val_loss: 0.5451
Epoch 6/100
4/4 [==============================] - 0s 6ms/step - loss: 0.4600 - val_loss: 0.5453
Epoch 7/100
4/4 [==============================] - 0s 5ms/step - loss: 0.4598 - val_loss: 0.5473
Epoch 8/100
4/4 [==============================] - 0s 5ms/step - loss: 0.4599 - val_loss: 0.5465
Epoch 9/100
4/4 [==============================] - 0s 6ms/step - loss: 0.4597 - val_loss: 0.5465
Epoch 10/100
4/4 [==============================] - 0s 6ms/step - loss: 0.4606 - val_loss: 0.5475
Epoch 11/100
4/4 [==========

In [ ]:
model.predict(x_test)

NameError: ignored